language: node_js
sudo: required

services:
  - docker

before_script:
  - docker-compose build
  - docker-compose up -d
  - sleep 5

script:
  - docker exec dockergaugecd_web_1 /bin/sh -c "cd /usr/src/app && npm run test"
  - docker-compose run sut test

branches:
  only:
    - master
